name: Debug SSH Connection

on:
    workflow_dispatch:  # Manual trigger only

jobs:
    debug_ssh:
        name: Test SSH Connection
        runs-on: ubuntu-latest
        
        steps:
            - name: Debug SSH Key
              run: |
                  echo "SSH Key length: ${#SERVER_SSH_KEY}"
                  echo "SSH Key starts with: $(echo "$SERVER_SSH_KEY" | head -c 50)"
                  echo "SSH Key ends with: $(echo "$SERVER_SSH_KEY" | tail -c 50)"
              env:
                  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
            
            - name: Test SSH with debug
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  debug: true
                  script: |
                      echo "SSH connection successful!"
                      whoami
                      pwd 