name: Staging Deployment

on:
    push:
        branches:
            - staging

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build_and_deploy:
        name: Build and Deploy to Staging
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                  platforms: 'arm64,arm'

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3
              with:
                  platforms: linux/amd64,linux/arm64/v8

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push staging image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  platforms: ${{ steps.buildx.outputs.platforms }}
                  push: true
                  tags: |
                      ghcr.io/swipe-one/emailengine:staging
                      ghcr.io/swipe-one/emailengine:staging-${{ github.sha }}

            - name: Deploy to staging server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      cd /opt/emailengine-fork
                      docker compose pull
                      docker compose up -d
                      docker system prune -f
                      echo "Deployment completed at $(date)" 